"""initial schema

Revision ID: 0001_initial_schema
Revises: 
Create Date: 2026-07-13 11:42:25.744404
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor_user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_actor_created', ['actor_user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('hospitals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('icu_type', sa.String(), nullable=False),
    sa.Column('total_beds', sa.Integer(), nullable=False),
    sa.Column('occupied_beds', sa.Integer(), nullable=False),
    sa.Column('supports_trauma', sa.Boolean(), nullable=False),
    sa.Column('supports_cardiac', sa.Boolean(), nullable=False),
    sa.Column('supports_neuro', sa.Boolean(), nullable=False),
    sa.Column('supports_pediatric', sa.Boolean(), nullable=False),
    sa.Column('supports_maternity', sa.Boolean(), nullable=False),
    sa.Column('has_ventilator_support', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ambulances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('call_sign', sa.String(), nullable=False),
    sa.Column('base_hospital_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('crew_contact', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ambulances', schema=None) as batch_op:
        batch_op.create_index('ix_ambulances_base_status', ['base_hospital_id', 'status'], unique=False)
        batch_op.create_index('ix_ambulances_status', ['status'], unique=False)

    op.create_table('icu_beds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=False),
    sa.Column('bed_no', sa.String(), nullable=False),
    sa.Column('icu_type', sa.String(), nullable=False),
    sa.Column('ward', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('fhir_location_id', sa.String(), nullable=True),
    sa.Column('operational_status', sa.String(), nullable=True),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'bed_no', name='uq_icu_beds_hospital_bed_no')
    )
    with op.batch_alter_table('icu_beds', schema=None) as batch_op:
        batch_op.create_index('ix_icu_beds_hospital_status', ['hospital_id', 'status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=True),
    sa.Column('ambulance_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ambulance_id'], ['ambulances.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_ambulance_id', ['ambulance_id'], unique=False)
        batch_op.create_index('ix_users_hospital_id', ['hospital_id'], unique=False)

    op.create_table('transfer_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('origin_hospital_id', sa.String(), nullable=False),
    sa.Column('destination_hospital_id', sa.String(), nullable=False),
    sa.Column('requested_by_user_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('patient_name', sa.String(), nullable=True),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('patient_sex', sa.String(), nullable=True),
    sa.Column('patient_blood_type', sa.String(), nullable=True),
    sa.Column('patient_allergies', sa.Text(), nullable=True),
    sa.Column('patient_emergency_contact', sa.String(), nullable=True),
    sa.Column('patient_identifier_value', sa.String(), nullable=True),
    sa.Column('patient_date_of_birth', sa.String(), nullable=True),
    sa.Column('patient_diagnosis', sa.Text(), nullable=True),
    sa.Column('patient_vitals_json', sa.Text(), nullable=True),
    sa.Column('patient_medications_json', sa.Text(), nullable=True),
    sa.Column('patient_infection_risk', sa.String(), nullable=True),
    sa.Column('patient_isolation_required', sa.Boolean(), nullable=False),
    sa.Column('handover_json', sa.Text(), nullable=True),
    sa.Column('patient_condition', sa.String(), nullable=False),
    sa.Column('required_icu_type', sa.String(), nullable=False),
    sa.Column('urgency_class', sa.String(), nullable=False),
    sa.Column('urgency_score', sa.Float(), nullable=False),
    sa.Column('ventilator_required', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ambulance_id', sa.String(), nullable=True),
    sa.Column('assigned_bed_id', sa.String(), nullable=True),
    sa.Column('route_payload_json', sa.Text(), nullable=True),
    sa.Column('pickup_latitude', sa.Float(), nullable=True),
    sa.Column('pickup_longitude', sa.Float(), nullable=True),
    sa.Column('dropoff_latitude', sa.Float(), nullable=True),
    sa.Column('dropoff_longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ambulance_id'], ['ambulances.id'], ),
    sa.ForeignKeyConstraint(['assigned_bed_id'], ['icu_beds.id'], ),
    sa.ForeignKeyConstraint(['destination_hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['origin_hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfer_requests', schema=None) as batch_op:
        batch_op.create_index('ix_transfer_requests_ambulance_status', ['ambulance_id', 'status'], unique=False)
        batch_op.create_index('ix_transfer_requests_assigned_bed', ['assigned_bed_id'], unique=False)
        batch_op.create_index('ix_transfer_requests_destination_status', ['destination_hospital_id', 'status'], unique=False)
        batch_op.create_index('ix_transfer_requests_origin_status', ['origin_hospital_id', 'status'], unique=False)
        batch_op.create_index('ix_transfer_requests_requested_by', ['requested_by_user_id'], unique=False)
        batch_op.create_index('ix_transfer_requests_status', ['status'], unique=False)

    op.create_table('patient_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=False),
    sa.Column('bed_id', sa.String(), nullable=False),
    sa.Column('patient_no', sa.String(), nullable=False),
    sa.Column('patient_name', sa.String(), nullable=False),
    sa.Column('identifier_system', sa.String(), nullable=True),
    sa.Column('identifier_value', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('blood_type', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('vitals_json', sa.Text(), nullable=True),
    sa.Column('medications_json', sa.Text(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('infection_risk', sa.String(), nullable=True),
    sa.Column('isolation_required', sa.Boolean(), nullable=False),
    sa.Column('emergency_contact', sa.String(), nullable=True),
    sa.Column('next_of_kin', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('transfer_id', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('admitted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bed_id'], ['icu_beds.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfer_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bed_id', name='uq_patient_records_bed_id')
    )
    with op.batch_alter_table('patient_records', schema=None) as batch_op:
        batch_op.create_index('ix_patient_records_hospital_id', ['hospital_id'], unique=False)
        batch_op.create_index('ix_patient_records_transfer_id', ['transfer_id'], unique=False)

    op.create_table('transfer_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transfer_id', sa.String(), nullable=False),
    sa.Column('actor_user_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfer_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfer_events', schema=None) as batch_op:
        batch_op.create_index('ix_transfer_events_actor_user', ['actor_user_id'], unique=False)
        batch_op.create_index('ix_transfer_events_transfer_created', ['transfer_id', 'created_at'], unique=False)

    op.create_table('bed_lifecycle_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bed_id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=False),
    sa.Column('actor_user_id', sa.String(), nullable=True),
    sa.Column('previous_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('transfer_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bed_id'], ['icu_beds.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_records.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfer_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bed_lifecycle_events', schema=None) as batch_op:
        batch_op.create_index('ix_bed_lifecycle_actor_user', ['actor_user_id'], unique=False)
        batch_op.create_index('ix_bed_lifecycle_bed_created', ['bed_id', 'created_at'], unique=False)
        batch_op.create_index('ix_bed_lifecycle_hospital_created', ['hospital_id', 'created_at'], unique=False)
        batch_op.create_index('ix_bed_lifecycle_patient', ['patient_id'], unique=False)
        batch_op.create_index('ix_bed_lifecycle_transfer', ['transfer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bed_lifecycle_events', schema=None) as batch_op:
        batch_op.drop_index('ix_bed_lifecycle_transfer')
        batch_op.drop_index('ix_bed_lifecycle_patient')
        batch_op.drop_index('ix_bed_lifecycle_hospital_created')
        batch_op.drop_index('ix_bed_lifecycle_bed_created')
        batch_op.drop_index('ix_bed_lifecycle_actor_user')

    op.drop_table('bed_lifecycle_events')
    with op.batch_alter_table('transfer_events', schema=None) as batch_op:
        batch_op.drop_index('ix_transfer_events_transfer_created')
        batch_op.drop_index('ix_transfer_events_actor_user')

    op.drop_table('transfer_events')
    with op.batch_alter_table('patient_records', schema=None) as batch_op:
        batch_op.drop_index('ix_patient_records_transfer_id')
        batch_op.drop_index('ix_patient_records_hospital_id')

    op.drop_table('patient_records')
    with op.batch_alter_table('transfer_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_transfer_requests_status')
        batch_op.drop_index('ix_transfer_requests_requested_by')
        batch_op.drop_index('ix_transfer_requests_origin_status')
        batch_op.drop_index('ix_transfer_requests_destination_status')
        batch_op.drop_index('ix_transfer_requests_assigned_bed')
        batch_op.drop_index('ix_transfer_requests_ambulance_status')

    op.drop_table('transfer_requests')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_hospital_id')
        batch_op.drop_index('ix_users_ambulance_id')

    op.drop_table('users')
    with op.batch_alter_table('icu_beds', schema=None) as batch_op:
        batch_op.drop_index('ix_icu_beds_hospital_status')

    op.drop_table('icu_beds')
    with op.batch_alter_table('ambulances', schema=None) as batch_op:
        batch_op.drop_index('ix_ambulances_status')
        batch_op.drop_index('ix_ambulances_base_status')

    op.drop_table('ambulances')
    op.drop_table('hospitals')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_entity')
        batch_op.drop_index('ix_audit_logs_actor_created')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
